apiVersion: extensions/v1beta1
kind: Ingress
metadata: # Config options of the object to create
  name: ingress-srv # Name of the entity to create
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
  